(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function savedWatchlist(){try{const value=JSON.parse(localStorage.getItem('gani.watchlist')||'[]');return Array.isArray(value)?value:[]}catch{return[]}}
const state={market:[],notices:[],accounts:[],profile:null,watchlist:new Set(savedWatchlist())};
const researchCatalog=[
  {id:'eur-usd',title:'EUR/USD',summary:'FX instrument reference for structure and macro research.',category:'fx'},
  {id:'gbp-usd',title:'GBP/USD',summary:'FX instrument reference for comparative research.',category:'fx'},
  {id:'gold',title:'Gold',summary:'Metals instrument reference for event and volatility review.',category:'metals'},
  {id:'btc-usd',title:'BTC/USD',summary:'Digital asset reference for liquidity and risk review.',category:'digital-assets'}
];
function mode(){try{return window.GANIAppData?.mode?.()||"mock"}catch{return"mock"}}
function esc(v){return String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]))}
function toast(m){const t=$("#toast");if(!t)return;t.textContent=m;t.classList.add("show");clearTimeout(toast.t);toast.t=setTimeout(()=>t.classList.remove("show"),1800)}
function show(id,push=true){if(!$("#"+id))id="home";$$('.screen').forEach(x=>x.classList.toggle('active',x.id===id));$$('[data-screen]').forEach(x=>x.classList.toggle('active',x.dataset.screen===id));$('#mobileMenu')?.classList.remove('open');$('#noticePanel')?.classList.remove('open');$('#searchPanel')?.classList.remove('open');if(push)history.replaceState(null,"","#"+id);window.scrollTo({top:0,left:0,behavior:'auto'});if(id==='dashboard')loadDashboard();if(id==='profile')loadProfile();if(id==='discover'||id==='markets')loadMarket()}
async function safe(fn){try{return await fn()}catch(e){toast(e?.message||'Data request failed');return null}}
function updateMode(){const m=mode().toUpperCase(),real=m==='REAL';['#dashMode','#profileMode','#homeMode','#settingsDataMode'].forEach(s=>{const el=$(s);if(el)el.textContent=m});if($('#marketMode'))$('#marketMode').textContent=real?'REAL API':'DEMO DATA';if($('#missionMarketMode'))$('#missionMarketMode').textContent=real?'REAL API':'DEMO DATA';if($('#heroMode'))$('#heroMode').textContent=real?'REAL API':'DEMO MODE';if($('#marketStripMode'))$('#marketStripMode').textContent=real?'API CONNECTED':'DEMO MODE';if($('#mobileMode'))$('#mobileMode').textContent=real?'REAL API':'DEMO MODE';if($('#mobileDataLabel'))$('#mobileDataLabel').textContent=real?'API connected':'Demo data'}
async function loadMarket(){const d=await safe(()=>GANIAppData.marketplace());if(!d)return;state.market=Array.isArray(d.items)?d.items:[];if($('#homeMarketCount'))$('#homeMarketCount').textContent=state.market.length;if($('#missionMarketCount'))$('#missionMarketCount').textContent=state.market.length;if($('#mobileMarketCount'))$('#mobileMarketCount').textContent=state.market.length;renderMarket()}
function renderMarket(){const el=$('#markets.active #missionMarketGrid')||$('#discover.active #marketGrid')||$('#missionMarketGrid')||$('#marketGrid');if(!el)return;const input=$('#markets.active #missionMarketSearch')||$('#discover.active #marketSearch');const q=input?.value.trim().toLowerCase()||'';const category=$('#marketCategory')?.value||'all';const watchOnly=$('#watchlistToggle')?.getAttribute('aria-pressed')==='true';const source=[...researchCatalog,...state.market.map(x=>({...x,id:x.id||`record-${x.title||x.name}`,category:x.category||'directory'}))];const items=source.filter(x=>(category==='all'||x.category===category)&&(!watchOnly||state.watchlist.has(x.id))&&JSON.stringify(x).toLowerCase().includes(q));if($('#watchlistCount'))$('#watchlistCount').textContent=state.watchlist.size;el.innerHTML=items.length?items.map((x,i)=>`<article class="market-card"><div class="market-card-top"><span class="tag">${esc(x.category||'directory')}</span><button class="watch-button ${state.watchlist.has(x.id)?'saved':''}" type="button" data-watch="${esc(x.id)}" aria-label="${state.watchlist.has(x.id)?'Remove from':'Add to'} watchlist">${state.watchlist.has(x.id)?'★':'☆'}</button></div><h3>${esc(x.title||x.name||'GANI Marketplace')}</h3><p>${esc(x.summary||x.description||'Reference entry available through GANI.')}</p><footer><span>${esc(x.mode==='demo'?'Demo record':'Reference only')}</span><b>${esc(x.status||'No quote')}</b></footer></article>`).join(''):`<article class="market-card market-no-results"><span class="tag">EMPTY STATE</span><h3>${watchOnly?'Your watchlist is empty':'No matching instruments'}</h3><p>${watchOnly?'Save a reference card with ☆ to build a personal list.':'Try another search or category.'}</p></article>`;$$('[data-watch]',el).forEach(b=>b.onclick=()=>{const id=b.dataset.watch;if(state.watchlist.has(id))state.watchlist.delete(id);else state.watchlist.add(id);localStorage.setItem('gani.watchlist',JSON.stringify([...state.watchlist]));renderMarket()})}
function localAssistant(text){const q=text.toLowerCase();if(q.includes('risk')||q.includes('loss'))return 'A useful risk checklist names the thesis, invalidation, maximum acceptable loss, position size and liquidity. Account-specific limits are unavailable until a supported account is connected.';if(q.includes('chart')||q.includes('pattern'))return 'Start with timeframe, market structure, support or resistance, and what would invalidate the idea. A pattern alone is not a verified signal.';if(q.includes('macro')||q.includes('event'))return 'Macro context can include rates, inflation, employment, policy and scheduled events. Confirm each item with a trusted source before relying on it.';return 'I can explain market concepts and help structure a review checklist locally. A connected AI backend is not available in this build.'}
function addAIMessage(author,text,kind='user'){const box=$('#aiMessages');if(!box)return;const row=document.createElement('div');row.className=`ai-message ${kind==='gani'?'ai-message-gani':''}`;row.innerHTML=`<b>${esc(author)}</b><p>${esc(text)}</p>`;box.append(row);row.scrollIntoView({block:'nearest'});}
async function loadNotices(){const d=await safe(()=>GANIAppData.notifications());if(!d)return;state.notices=Array.isArray(d.items)?d.items:[];renderNotices()}
function noticeHTML(n){return `<div class="notice-row ${n.read?'':'unread'}" data-notice="${esc(n.id)}"><div class="notice-icon">${n.read?'✓':'•'}</div><div><b>${esc(n.title||'Notification')}</b><small>${n.read?'Read':'Unread'}</small></div>${n.read?'':`<button class="status-pill read-one">Mark read</button>`}</div>`}
function renderNotices(){const h=state.notices.length?state.notices.map(noticeHTML).join(''):'<p class="hint">No notifications.</p>';if($('#noticeList'))$('#noticeList').innerHTML=h;if($('#dashboardNotices'))$('#dashboardNotices').innerHTML=h;const unread=state.notices.filter(n=>!n.read).length;if($('#unreadCount'))$('#unreadCount').textContent=unread;if($('#homeNoticeCount'))$('#homeNoticeCount').textContent=unread;if($('#mobileNoticeCount'))$('#mobileNoticeCount').textContent=unread;$('#noticeDot')?.classList.toggle('on',unread>0);$$('.read-one').forEach(b=>b.onclick=async()=>{const id=b.closest('[data-notice]').dataset.notice;await safe(()=>GANIAppData.markNotificationRead(id));await loadNotices()})}
async function loadAccounts(){const d=await safe(()=>GANIAppData.accounts());if(!d)return;state.accounts=Array.isArray(d.items)?d.items:[];if($('#accountCount'))$('#accountCount').textContent=state.accounts.length;if($('#homeAccountCount'))$('#homeAccountCount').textContent=state.accounts.length;if($('#mobileAccountCount'))$('#mobileAccountCount').textContent=state.accounts.length;if($('#accountList'))$('#accountList').innerHTML=state.accounts.length?state.accounts.map(a=>`<div class="account-row"><div class="account-icon">◎</div><div><b>${esc(a.name||a.id||'Account')}</b><small>${esc(a.provider||a.mode||'GANI')}</small></div><span class="status-pill">${esc(a.status||'active')}</span></div>`).join(''):'<p class="hint">No accounts available.</p>'}
async function loadProfile(){const p=await safe(()=>GANIAppData.me());if(!p)return;state.profile=p;const name=p.name||'GANI User';[['#profileName',name],['#profileName2',name],['#profileId',p.id||'—'],['#profileVerified',p.verified?'Verified':'Not verified'],['#verifiedBadge',p.verified?'✓ Verified':'Unverified'],['#profileState',p.verified?'Customer profile verified':'Customer profile'],['#profileSource',mode().toUpperCase()]].forEach(([s,v])=>{const e=$(s);if(e)e.textContent=v})}
async function loadDashboard(){updateMode();await Promise.all([loadAccounts(),loadNotices()])}
async function verify(){const ref=$('#verifyInput').value.trim(),box=$('#verifyResult');if(!ref){toast('Enter a GANI reference');return}box.className='verify-result';box.innerHTML='<div class="skeleton"></div>';const r=await safe(()=>GANIAppData.verify(ref));if(!r){box.innerHTML='<div class="verify-ring"><span>!</span></div><small>VERIFICATION</small><h3>Unable to verify</h3><p>Check the data source and try again.</p>';return}const ok=String(r.status).toLowerCase()==='verified';box.className='verify-result '+(ok?'success':'fail');box.innerHTML=`<div class="verify-ring"><span>${ok?'✓':'!'}</span></div><small>VERIFICATION</small><h3>${ok?'Verified':'Not verified'}</h3><p>${esc(r.reference||ref)}</p><span class="status-pill ${ok?'':'neutral'}">${esc(r.mode||mode())}</span>`}
function bind(){
  $$('[data-screen]').forEach(b=>b.addEventListener('click',e=>{e.preventDefault();show(b.dataset.screen)}));
  $$('[role="button"][data-screen]').forEach(b=>b.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();show(b.dataset.screen)}}));
  $('#menuToggle').onclick=()=>$('#mobileMenu').classList.toggle('open');
  $('#searchToggle').onclick=()=>{$('#searchPanel').classList.add('open');$('#globalSearch').focus()};
  $('#searchClose').onclick=()=>$('#searchPanel').classList.remove('open');
  $('#noticeToggle').onclick=()=>{$('#noticePanel').classList.toggle('open');loadNotices()};
  $('#noticeClose').onclick=()=>$('#noticePanel').classList.remove('open');
  $('#marketSearch').oninput=renderMarket;$('#missionMarketSearch').oninput=renderMarket;$('#verifyBtn').onclick=verify;$('#verifyInput').onkeydown=e=>{if(e.key==='Enter')verify()};
  $('#marketCategory')?.addEventListener('change',renderMarket);$('#watchlistToggle')?.addEventListener('click',e=>{const on=e.currentTarget.getAttribute('aria-pressed')!=='true';e.currentTarget.setAttribute('aria-pressed',String(on));renderMarket()});
  $('#aiCompose')?.addEventListener('submit',e=>{e.preventDefault();const input=$('#aiInput'),text=input.value.trim();if(!text)return;addAIMessage('You',text);input.value='';setTimeout(()=>addAIMessage('GANI AI',localAssistant(text),'gani'),180)});$$('[data-prompt]').forEach(b=>b.addEventListener('click',()=>{const input=$('#aiInput');input.value=b.dataset.prompt;input.focus()}));
  $('#signalFilter')?.addEventListener('change',e=>$$('[data-signal-type]').forEach(card=>{card.hidden=e.target.value!=='all'&&card.dataset.signalType!==e.target.value}));
  $$('[data-demo-action]').forEach(b=>b.addEventListener('click',()=>toast(`${b.dataset.demoAction}: available in a later milestone`)));
  $('#refreshDashboard').onclick=loadDashboard;
  $('#markAllRead').onclick=async()=>{for(const n of state.notices.filter(n=>!n.read))await safe(()=>GANIAppData.markNotificationRead(n.id));await loadNotices()};
  $('#globalSearch').onkeydown=e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();$('#searchPanel').classList.remove('open');if(q.includes('ver')||q.includes('tool'))show('verify');else if(q.includes('account')||q.includes('analytic')||q.includes('dash'))show('dashboard');else if(q.includes('profile'))show('profile');else if(q.includes('learn')||q.includes('edu'))show('education');else if(q.includes('support')||q.includes('help'))show('support');else{show('discover');$('#marketSearch').value=e.target.value;renderMarket()}}};
  window.addEventListener('hashchange',()=>show(location.hash.slice(1)||'home',false));
}
window.addEventListener('DOMContentLoaded',async()=>{bind();updateMode();show(location.hash.slice(1)||'home',false);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js',{updateViaCache:'none'}).catch(()=>{});await Promise.all([loadMarket(),loadNotices(),loadAccounts(),loadProfile()])});
})();
