(()=>{"use strict";
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const key="gani-platform-v27";
const data=()=>{try{return JSON.parse(localStorage.getItem(key))||{}}catch{return{}}};
const save=x=>localStorage.setItem(key,JSON.stringify(x));
const esc=v=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[c]));
const stamp=()=>new Date().toLocaleDateString("so-SO",{year:"numeric",month:"short",day:"numeric"});
const rules=[
 ["01","Customer Terms","Adeegga GANI, adeegga partner-ka, u-qalmitaanka, account-ka qofka iyo mas'uuliyadda."],
 ["02","Partner Agreement","Komishan, SLA, payout, refund, cabasho, xog, audit iyo joojinta iskaashiga."],
 ["03","Risk & Refund","Khatarta evaluation-ka, sababaha xiritaanka, refund-ka iyo jidka rafcaanka."],
 ["04","Privacy & Security","Xogta la ururiyo, sababta, muddada la hayo, cidda lala wadaago iyo xuquuqda qofka."],
 ["05","Complaints & Appeals","Ticket, caddayn, waqtiga jawaabta, escalation iyo natiijada qoraalka ah."],
 ["06","Country Eligibility","Dalalka, residency, nationality, payment iyo payout availability."],
 ["07","EA & Automation","Robot, copy trading, VPS, IP, news trading iyo xeeladaha la oggol yahay."],
 ["08","Payments & Payouts","Qiime, receipt, komishan, refund, payout schedule iyo muranka lacagta."]
];
function modal(title,body){let m=$("#v27Modal");if(!m){m=document.createElement("div");m.id="v27Modal";m.className="v27-modal";m.hidden=true;document.body.append(m)}m.innerHTML=`<div class="v27-modal-card"><div class="v27-modal-head"><h3>${esc(title)}</h3><button aria-label="Xir">×</button></div><div class="v27-modal-body">${body}</div></div>`;m.hidden=false;m.querySelector("button").onclick=()=>m.hidden=true;m.onclick=e=>{if(e.target===m)m.hidden=true};return m}
function render(){const d=data(),apps=d.applications||[],tickets=d.tickets||[],payments=d.payments||[],agreements=d.agreements||[],ready=d.readiness||{};$("#v27AppCount")&&($("#v27AppCount").textContent=apps.length);$("#v27TicketCount")&&($("#v27TicketCount").textContent=tickets.length);$("#v27AgreementCount")&&($("#v27AgreementCount").textContent=agreements.length);const score=Math.round(Object.values(ready).filter(Boolean).length/5*100)||0;$("#v27ReadyState")&&($("#v27ReadyState").textContent=score+"%");$("#v27ReadinessBadge")&&($("#v27ReadinessBadge").textContent=score===100?"Diyaar":score?"Socda":"Bilow");
 const records=(arr,empty)=>arr.length?arr.map(x=>`<div class="v27-record"><div><b>${esc(x.title)}</b><small>${esc(x.detail||x.date)}</small></div><span>${esc(x.status)}</span></div>`).join(""):`<p class="hint">${empty}</p>`;
 $("#v27Applications")&&($("#v27Applications").innerHTML=records(apps,"Dalab wali lama samayn."));$("#v27Tickets")&&($("#v27Tickets").innerHTML=records(tickets,"Ticket wali ma jiro."));$("#v27Payments")&&($("#v27Payments").innerHTML=records(payments,"Diiwaan lacag wali ma jiro."));
 $$("#readinessForm input").forEach(x=>x.checked=!!ready[x.name]);
}
function application(plan="Self-service"){const m=modal("Dalab cusub",`<form id="v27ApplicationForm"><label>Adeegga<select name="plan"><option>${esc(plan)}</option><option>Self-service</option><option>GANI Assist</option><option>Business</option></select></label><label>Waxaad u baahan tahay<textarea name="goal" required placeholder="Sharax adeegga ama account-ka aad rabto"></textarea></label><label>Platform-ka<input name="platform" placeholder="MT5, cTrader ama kale"></label><div class="v27-form-actions"><button class="primary">Kaydi dalabka</button></div></form>`);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.applications=d.applications||[];d.applications.unshift({title:f.get("plan"),detail:(f.get("platform")||"Platform wali lama dooran")+" • "+stamp(),status:"LA HELAY",goal:f.get("goal")});save(d);m.hidden=true;render()}}
function payment(){const m=modal("Ku dar receipt",`<form id="v27PaymentForm"><label>Order ama receipt ID<input name="reference" required></label><label>Partner-ka<input name="partner" required></label><label>Nooca<select name="type"><option>Challenge fee</option><option>GANI Assist</option><option>Refund</option><option>Payout</option></select></label><div class="v27-form-actions"><button class="primary">Kaydi diiwaanka</button></div></form>`);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.payments=d.payments||[];d.payments.unshift({title:f.get("type")+" • "+f.get("reference"),detail:f.get("partner")+" • "+stamp(),status:"DIIWAAN"});save(d);m.hidden=true;render()}}
function ticket(){const m=modal("Fur ticket",`<form id="v27TicketForm"><label>Qaybta<select name="topic"><option>Account</option><option>Payment</option><option>Refund</option><option>Payout</option><option>Rules</option><option>Technical</option></select></label><label>Faahfaahinta<textarea name="message" required></textarea></label><div class="v27-form-actions"><button class="primary">Gudbi ticket</button></div></form>`);m.querySelector("form").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.tickets=d.tickets||[];d.tickets.unshift({title:f.get("topic"),detail:f.get("message")+" • "+stamp(),status:"FURAN"});save(d);m.hidden=true;render()}}
function bind(){if($("#v27Rules"))$("#v27Rules").innerHTML=rules.map(r=>`<article class="v27-rule"><span>${r[0]}</span><h3>${r[1]}</h3><p>${r[2]}</p><button class="secondary v27-read-rule" data-rule="${r[1]}">Akhri oo aqbal</button></article>`).join("");
 $$(".v27-start").forEach(b=>b.onclick=()=>application(b.dataset.plan));$("#newApplication")&&($("#newApplication").onclick=()=>application());$("#addPayment")&&($("#addPayment").onclick=payment);$("#newTicket")&&($("#newTicket").onclick=ticket);
 $("#readinessForm")&&($("#readinessForm").onsubmit=e=>{e.preventDefault();const d=data();d.readiness={};new FormData(e.target).forEach((_,k)=>d.readiness[k]=true);save(d);render()});
 $$(".v27-read-rule").forEach(b=>b.onclick=()=>{const r=rules.find(x=>x[1]===b.dataset.rule),m=modal(r[1],`<p>${esc(r[2])}</p><p>Qoraalka production-ka waxaa lagu xiraa version, taariikhda dhaqan-galka iyo partner-ka uu khuseeyo.</p><div class="v27-form-actions"><button class="primary" id="v27AcceptRule">Waan akhriyey</button></div>`);m.querySelector("#v27AcceptRule").onclick=()=>{const d=data();d.agreements=d.agreements||[];if(!d.agreements.some(x=>x.title===r[1]))d.agreements.push({title:r[1],date:stamp(),status:"LA AQBALAY"});save(d);m.hidden=true;render()}});
 $("#partnerApply")&&($("#partnerApply").onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),d=data();d.partnerApplications=d.partnerApplications||[];d.partnerApplications.push({company:f.get("company"),website:f.get("website"),status:"REVIEW",date:stamp()});save(d);e.target.reset();modal("Codsiga waa la helay","<p>Partner application-ka waa la diiwaangeliyey. Aqoonsiga, domain-ka, waddamada iyo heshiiska ayaa xiga.</p>")});
 render()}
window.addEventListener("DOMContentLoaded",bind);
})();
